application: canvas-copter
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /levels
  static_dir: levels
- url: /src
  static_dir: src
- url: /
  static_files: index.html
  upload: index.html